version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  node-app:
    build: ./gate-simulator/
    image: node-app:1.0
    ports:
      - '9999:9999'

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass